project:
  type: website
  output-dir: "."

website:
  title: "Jaxson Marsh"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: Classwork
        href: classwork-10.qmd
  page-footer:
    center: "Powered with GitHub and Quarto<br>© Jaxson Marsh, 2023"

format:
  html:
    theme: 
      light: minty
      dark: quartz
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
